### ISSUE TITLE
Why a correction

### ISSUE THREAD

**Issue by jxl77** [SndrSchnklshk/HDC302x#1]
Hello, 

Why do you add a correction on humidity that is not in the datasheet ?

 readDataResult.Humidity = readDataResult.Humidity - 1.20;             // Correction

My impression is that this is wrong in general. Of course, a given  sensor may need a correction, but this should not apply in the general case. 

Best Wishes

**Comment by SndrSchnklshk** [comment]
Hey!

Thanks for your report this issue! You are absolutely right. Not great to have this value hard-coded!

There might be a better way with a programmed offset. See 8.5.7.5.3 Calculate Relative Humidity Offset Value on page 26.

For now, I have added the `setHumidityCorrection(...)` method, but by default it's zero. Hope it helps!

**Comment by SndrSchnklshk** [comment]
Get latest to try.
