### ISSUE TITLE
Buffer size issue causes uncertain behaviors

### ISSUE THREAD

**Issue by Zia0815** [SndrSchnklshk/HDC302x#2]
In the function HDC302xDataResult HDC302x::ReadData() of the HDC302x.cpp file, the data that is returned by the slave device is stored in a uint8_t buffer[4] (located in HDC302x.h file) variable. But the data that is being send by the slave device is of 6bytes. This results in the MCU to restart unexpectedly, sometimes the i2c bus hangs and sometimes it works. After a lot of poking around I found that the buffer was the culprit. I changed the buffer size to 8 and now my device runs smoothly.

**Comment by SndrSchnklshk** [comment]
Hi @Zia0815, Thanks for letting me know. Weirdly i have never encountered this issue myself. Which HDC302 sensor (type) do you use? 

I will investigate and pack it in a new release later...

**Comment by SndrSchnklshk** [comment]
Buffer size has been increased to 6.
